### ISSUE TITLE
Mention array of things (like `object[ID]`)

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#114]
There are some array of game entities that are available like `object[ID]`, `hotspot[ID]` and `inventory[ID]` (not sure if this is a thing?) and I can't seem to figure out if they are mentioned in the manual or not :/ 

I think these need to be somewhere and mentioned in the ID property of things. I don't know where properly include so it's searchable and can be in the see also of where it makes sense.

I noticed this only today watching Dave's Dev stream.

**Comment by ivan-mogilko** [comment]
Hmm right, I dont know if these are mentioned too.

These arrays are auto-generated, and they also have this problem that they are not generated if there's no items, because in AGS script array cannot have 0 size, so if you have "inventory" in your script then the game *must* have at least 1 inventory item created to make this script compile.

I think this may be seen as a part of Script API, maybe make a topic like "global objects", or "object arrays".

**Comment by ivan-mogilko** [comment]
Found it in code: https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Types/Game.cs#L16

**Comment by ericoporto** [comment]
Thanks! I did looked in `agsdfns.sh` as a first instinct but could not find it there xD

Oh, I had similar name in mind but need to think a bit more if it will be confusing - because ags has objects meaning other thing. In any way, I checked that there are none of the lowercase variant in the index so these would be a first, need to test locally if these would indeed appear separately in the index of the chm file, otherwise I would move them to a topic like "referencing ags entities by ID".

**Comment by ericoporto** [comment]
```
Hotspot hotspot[AGS_MAX_HOTSPOTS];
Region region[AGS_MAX_REGIONS];
Object object[AGS_MAX_OBJECTS];

InventoryItem inventory[Game.InventoryItemCount]
GUI gui[]
Dialog dialog[]
```

I think there's also a `character[]` but I think I missed in the code above.

**Comment by ivan-mogilko** [comment]
Added "Global Arrays" article: https://github.com/adventuregamestudio/ags-manual/wiki/GlobalArrays
Linked at Scripting API.
