### ISSUE TITLE
Wiki home bugged

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#128]
Is it just me who is seeing a ton of XML on the wiki home?

https://github.com/adventuregamestudio/ags-manual/wiki

@morganwillcock I wonder if there's something wrong with the GitHub actions

Also the commit history in the web ui is lying.

**Comment by morganwillcock** [comment]
> Is it just me who is seeing a ton of XML on the wiki home?
> 
> https://github.com/adventuregamestudio/ags-manual/wiki

I think it is a rendering issue on the site, if I keep clicking the wiki 'tab' it sometimes loads correctly and sometimes reverts to displaying the HTML source. 
 
> @morganwillcock I wonder if there's something wrong with the GitHub actions

It is a separate repository that is only referenced for cloning, so it shouldn't write anything back there. You can see it is internal to GitHub and not from Pandoc because it is referencing classes such as 'octicon'.

> Also the commit history in the web ui is lying.

I would only trust the actual repository, and that looks OK.

**Comment by ericoporto** [comment]
Ah, thanks! I was curious if there was something else but you are right, things are alright now.
