### ISSUE TITLE
dead link in wiki sidebar

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags-manual#129]
when clicking on "Calling global functions from local scripts" i get redirected to "create new page" entry.

btw is there an index listing all script functions ?

**Comment by morganwillcock** [comment]
> when clicking on "Calling global functions from local scripts" i get redirected to "create new page" entry.

Thanks. It seems there are 3 broken links:

CallingGlobalFunctions.md
BuiltInEnums.md
Reference.md

The sidebar isn't used anywhere except the GitHub wiki, so it isn't validated in any way. It isn't obvious what has happened to 2 of those pages, but I'll try to work it out.

> btw is there an index listing all script functions ?

Unfortunately not because the lookups from the Editor are against the top level of the index. And there is no manually maintained list because that would (did) become broken like the sidebar. Technically the metadata files from the build process would define them all, so creating a list is possible. Or you can probably approximate it by searching the wiki source:

```
egrep '^###\s+`' *.md | cut -d'`' -f2 | sort
```

In an ideal world I think the function documentation needs to be alongside the function in the program source so that it cannot be out-of-sync. And possibly that has to happen now; it is likely that at some point functions will be added or removed and the change won't go to all branches.

**Comment by ivan-mogilko** [comment]
> btw is there an index listing all script functions ?

Not index, but the closest is the topic list where script functions are grouped into categories:
https://github.com/adventuregamestudio/ags-manual/wiki/Scripting

The does not let see them altogether alphabetically, but at least thematically.

**Comment by rofl0r** [comment]
> In an ideal world I think the function documentation needs to be alongside the function in the program source so that it cannot be out-of-sync. And possibly that has to happen now; it is likely that at some point functions will be added or removed and the change won't go to all branches.

that's a good idea.

> The does not let see them altogether alphabetically, but at least thematically.

i've been looking at it, but it's not satifsfying. to get an overview of what one can do one has to click 10+ subcategories (and scroll over sometimes rather long descriptive texts). i guess i'll just look at the C++ code exporting the script functions instead.

**Comment by ivan-mogilko** [comment]
>  i guess i'll just look at the C++ code exporting the script functions instead.

There's also a script header that lists these functions, if you just need a full list of their names:
https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Editor/Resources/agsdefns.sh

**Comment by rofl0r** [comment]
> But I may not understand what form of information exactly you are looking for.

a single, alphabetic index/list of all functions with link to their definition, optimally with prototype

example:
```
int close(int fd);
int open(char*, int, ...);
void puts(char*);
...
```
this allows one to figure out available functionality with one glance and quickly look for a function containing e.g. "load" with ctfl-f.

> For instance, in C++ code the list of those functions is also split into many files.

oh. i thought last time i looked at it it was a huge blob of function declarations, but it was some years ago.

so it's probably best to extract the list from .md files as morgan suggested.

**Comment by morganwillcock** [comment]
I've [fixed or removed](https://github.com/adventuregamestudio/ags-manual/wiki/_Sidebar/_compare/f4ed7ed96b73eb7513b066433dcccc8c85e3e325...c7d53cbce2220a05ed0683201219717952df6e6c) the broken links. Is it OK to close the issue @rofl0r ?

**Comment by rofl0r** [comment]
thanks!
