### ISSUE TITLE
allow creating manual releases from the GitHub Release interface

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#137]
for now it's not possible to use the release interface and instead new releases have to be done by pushing a new tag from the manual git remotely (see https://github.com/adventuregamestudio/ags-manual/issues/136#issuecomment-847884537).

It's probable a config in the release.yml pipeline to allow for release/tag rewrite so that it can edit/rewrite the release to push the new assets/overwrite them.

**Comment by ericoporto** [comment]
In true Microsoft fashion their own GitHub Actions we use to push the release in our workflow is now unmaintained and archived, need to figure a NEW and MAINTAINED action to do this.

**Comment by morganwillcock** [comment]
It is described in #126, but yes, the problem is that the available actions are limited in what they can do. This was actually the second one that I tried, the first assumed that you could run rsync so it wouldn't work on the native Windows tasks.

I am testing build changes at the moment (for mostly unrelated reasons) but I don't see we can do much differently for the upload mechanism. If GitHub doesn't let you create a tag in the web interface and GitHub doesn't provide a usable release mechansim for its own CI service, then I'm not sure what to suggest. If the long term plan is to run all the builds here then at least everything will have the same problem and that will remove the inconsistency...
