### ISSUE TITLE
better per file checksum check

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#146]
so, currently checksum between platforms is broken : https://github.com/adventuregamestudio/ags-manual/actions/runs/977410949. 

I understand the idea behind this check but I think it's not useful as is, since it doesn't drill down and shows where the missmatch is, making hard to fix things.

**Comment by morganwillcock** [comment]
Yes, it isn't very good right at the moment so unfortunately you would have to download the zip files and compare the directories. I'm testing various changes at the moment and one of these is switching to downloading the files and comparing them for you, and that should print the differences:
https://github.com/morganwillcock/ags-manual/blob/9f6fe8f7fbde63ca81d5d493becd716136084882/.github/workflows/test.yml#L173-L192

The actual problem seems to be an encoding error, I retried building on what I have setup right now and it shows failures when writing the metadata files. This would also align with content in the search.js and genindex.html file being missing - if you compare the HTML contents it looks as though the macOS and Windows build had part of the wiki content missing. I guess that the custom writer might not have a fixed encoding specified and so it only fails when the output is using a custom writer - perhaps that is actually the underlying problem although in this case the content looks a little strange...

The top line here is from one of the new wiki pages, and the bottom line is where I've deleted the indent and re-added it using the space bar.
<pre>
                       PluginObject_DoSomething);
                       PluginObject_DoSomething);
</pre>

It looks like the top line is using non-breaking spaces instead of regular spaces:
<pre>
<span class="hexl-address-region">00000000:</span> c2a0 c2a0 c2a0 c2a0 c2a0 c2a0 c2a0 c2a0  <span class="hexl-ascii-region">................</span>
<span class="hexl-address-region">00000010:</span> c2a0 c2a0 c2a0 c2a0 c2a0 c2a0 c2a0 c2a0  <span class="hexl-ascii-region">................</span>
<span class="hexl-address-region"><span class="highlight"><span class="highlight">00000020:</span></span></span> c2a0 c2a0 c2a0 c2a0 c2a0 c2a0 2050 6c75  <span class="hexl-ascii-region">...........</span><span class="hexl-ascii-region"><span class="highlight">.</span></span><span class="hexl-ascii-region"> Plu</span>
<span class="hexl-address-region">00000030:</span> 6769 6e4f 626a 6563 745f 446f 536f 6d65  <span class="hexl-ascii-region">ginObject_DoSome</span>
<span class="hexl-address-region">00000040:</span> 7468 696e 6729 3b0a 2020 2020 2020 2020  <span class="hexl-ascii-region">thing);.        </span>
<span class="hexl-address-region">00000050:</span> 2020 2020 2020 2020 2020 2020 2020 2050  <span class="hexl-ascii-region">               P</span>
<span class="hexl-address-region">00000060:</span> 6c75 6769 6e4f 626a 6563 745f 446f 536f  <span class="hexl-ascii-region">luginObject_DoSo</span>
<span class="hexl-address-region">00000070:</span> 6d65 7468 696e 6729 3b                   <span class="hexl-ascii-region">mething);</span>
</pre>
...and for some reason it looks like the failure doesn't occur on the Ubuntu runner, but does on the Windows and macOS runner. It could be an issue with specific versions of Pandoc (one of the other changes I'm trying to test the Pandoc before using it) but for this particular problem it is probably best to retry after cleaning up these spaces.

**Comment by ericoporto** [comment]
So, I obviously didn't retype everything from the website, like ran a thing and used the result and then fixed stuff around by hand. But I don't fully understand what you've said about the encoding - it was supposed to be UTF-8 according to my text editor. 

I tried to do what I thought you said [here in this commit](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/6853a2167684c1e489618ef6495d18c4f48741f1...8d44d73b4c1cc64236629c530d03262ec6142641), but it didn't work. I tried using [ftfy](https://ftfy.readthedocs.io/en/latest/cli.html) too, but it didn't change a single bit.

**Comment by morganwillcock** [comment]
The error should have cleared now. I think the exit code on the metadata generation is hidden by the string check on its output, so the metadata needs to be built in a separate step which can fail on its own in order for errors there to be flagged up.

**Comment by ericoporto** [comment]
Thanks, it's building now after your change!

**Comment by morganwillcock** [comment]
I switched this as part of the build system change. Located Pandoc binaries are tested for the non-breaking space issue (it seemed to be platform and version specific so rejecting based on version number wouldn't work). The diff process recursively runs on pairs of built website directories and the diff output should be visible in the CI logs.
