### ISSUE TITLE
Upgrading to 3.6.0 entry

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#158]
So, I noticed we didn't make a Upgrading to 3.5.1 entry, although we had one for 3.4.1, but I think we should do a Upgrading to 3.6.0 entry in the manual.

This issue is to track the writing of such entry and get ideas of things to include in it! These entries usually don't have a full changelog, but instead show "things of note" on it.

I guess we need a small intro about backend change - something small. One feature that I want to mention is being able to pack arbitrary files. Any other ideas welcome.

**Comment by ivan-mogilko** [comment]
An entry could be added for 3.5.1 if necessary, it was more important for 3.4.1 in comparison, because 3.4.1 changed subfolder structure in Compiled.

There's no direct rule to what put in these articles, but priority goes to
* things that change the workflow in the editor;
* big new features (example is multiple cameras);
* deprecated script api
* removed limits

**Comment by ivan-mogilko** [comment]
Draft plan (in major points):
* Unicode support
* Changes to key input handling (also related to unicode)
* Building for Android and Web in the editor
* Fonts update (TTF sizes, outlines)
* Game package update: custom files, $DATA$, multi-voxes, sprite compression options.
* Overlays improvement (lots of them, so should mention here)
* Deprecated stuff: things cut off from the engine, including Game Explorer, and things not supported with the new backend
* Deprecated API (Object.IgnoreScaling -> Object.ManualScaling)
* System limits update

**Comment by ivan-mogilko** [comment]
Started writing (in progress): https://github.com/adventuregamestudio/ags-manual/wiki/UpgradeTo36
