### ISSUE TITLE
Web: Searching for Character.Say gets no results

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#201]
All of the struct methods in the titles, like System.Log, Character.Say, if you search any of these, they get no results. Looking the JS index, only the methods (Log, Say) are indexed, and also the structs, but there's no additional indexing of the combination.

**Comment by morganwillcock** [comment]
I think the search data is currently split on words.

In the short term the best thing to do is probably to make additional words filter the results from the just word. So "System Log" would show pages that contain "System" and "Log", instead of what it does now, showing all pages which contain "System" or "Log". To be honest I'm not sure why I didn't do it that way to start with as additional filtering is probably much more useful than matching additional pages.

But the proper fix is a better index. Some decisions for the index data were to try to keep the CHM viewer usable (e.g. give scrollbar motion on the index that is actually usable).

**Comment by ivan-mogilko** [comment]
> But the proper fix is a better search index. The CHM index is generated automatically by HHC or chmcmd but the content of those varies between the two. I think HHC must be splitting words into partial words for better searching and its search index is much bigger.

Might that be a good long term goal to replace CHM with a html pages on disk instead? I think a lot of software do that today. We could have similar output for online and offline help, and users will need a browser to read offline one.

Of course I would suggest a html page redesign, because current one has limited functionality at the moment (in terms of index and table of contents).

**Comment by morganwillcock** [comment]
Maybe it is the sort of thing that could be integrated into the development tools, i.e. the development tools include provide everything for editor support (LSP server, documentation server, documentation content). Then an (any) editor can request help content from the tools, and either display the content that is returned or ask the user's regular browser to open a URL, which then views the documentation page, served by a web server built into the tools.

Having the option of the data going directly back to an editor would allow the possibility that the editor could re-implement whatever type of window focus rules best suit the current editor state - I think that is probably the main argument in favour of keeping the CHM viewer, the behaviour of its window can be altered so that it co-exists nicely with windows from the main application.

Just having HTML pages on disk and nothing else is probably going to be more difficult to search.

**Comment by ericoporto** [comment]
> In the short term the best thing to do is probably to make additional words filter the results from the just word. So "System Log" would show pages that contain "System" and "Log"

This is good enough, do you know if it's possible to do this using the current index? So System.Log would become "System AND Log" logic wise in the query.

**Comment by AlanDrake** [comment]
Yes, it's possible. We just have to pretend the "." is an empty space.
I wanted to make a PR with some quality of life, I'll just add this change too.

**Comment by morganwillcock** [comment]
It looks like when the index data is generated it does preserve a `-` in the middle of the word, so it might be worth trying to do the same test and adjustment of the match pattern with a `.`.
https://github.com/adventuregamestudio/ags-manual/blob/7083ef9d4673f141c686c52c0c433b00746083b6/lua/write_metablock.lua#L88-L100

**Comment by AlanDrake** [comment]
Alright, then I'll skip turning periods into spaces.
In the meanwhile I wrapped up my proposed changes in PR #202

Not sure yet if it compiles fully. On my rig I set up only the bare minimum to produce htmls directly with pandoc without the makefile, many things don't work obviously. I should set it up on a VM with linux to try it properly.

**Comment by morganwillcock** [comment]
I think this would be enough to make it work without causing too many issues:
```diff
diff --git a/lua/write_metablock.lua b/lua/write_metablock.lua
index 8bdfd90c..505fa900 100644
--- a/lua/write_metablock.lua
+++ b/lua/write_metablock.lua
@@ -90,6 +90,11 @@ function add_word(word)
     chars = chars .. '-'
   end
 
+   -- preserve . in the middle of the word
+  if first ~= '.' and last ~= '.' then
+    chars = chars .. '%.'
+  end
+
   -- split on non-word characters
   for w in word:gmatch('[' .. chars .. ']+') do
     if w:len() > 1 and not w:match('%d') then
```
...this is effectively reclassifying "." as part of a word. The will be some side effects for where existing entries get extended to include the ".", but in terms of searching for the scripting language syntax I think it should be OK.

**Comment by AlanDrake** [comment]
I just realized we had never applied this patch. It's been applied, and I've also added underscore and escaped `%-`.

In theory that should cover all needs for keywords searching.
