### ISSUE TITLE
[3.6.1] Document Log Panel

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#219]
Subj.

**Comment by ericoporto** [comment]
Here’s a small sketch;


The Log Panel in AGS Editor can help you understand issues in your game by showing warning messages and other issues raised by internal AGS engine logic or just by helping you follow some behavior in your own script by let you read the logs you add for debug purposes.

The Log Panel can show messages from the following Log Groups

- Script, which are generated by calling System.Log in your own functions 
- Game, which are messages generated by the AGS Engine internal game logic
- Main, which are messages generated by the AGS Engine relative to the interface between the engine and the platform/system it's running on

Note: the Script group log messages can still be found in release builds of your game by running it through command line and passing the necessary flags.

You can silence the log output at any time and have it printing back by clicking pause or run buttons at top left. By default it will scroll following the latest message added, but this can be disabled by clicking on the auto glue button.

Additional buttons are available for copying and clearing the message buffer- note any time you start a new debug session the messages are cleared by default.

**reference**

- https://developer.android.com/studio/debug/logcat
- 

Need to add a see also for


- [Runtime Engine](https://github.com/adventuregamestudio/ags-manual/wiki/RuntimeEngine#command-line), because of the file logging 
- [System.Log](https://github.com/adventuregamestudio/ags-manual/wiki/System#systemlog)
- [LogLevel Enum](https://github.com/adventuregamestudio/ags-manual/wiki/StandardEnums#loglevel), the only reference to the order of priority 
  - probably some explanation of what the filter means , that if you have a 3 you also get something from 2 and 1 and things like this

**Comment by ericoporto** [comment]
I am trying to figure out how to explain this, but sometimes when making a game you are happy to throw a debug breakpoint, but sometimes you need to monitor a continually changing value or you want to see if a function is reached without interrupting the flow, so at these cases you probably want to use System.Log.

Not sure if relevant but maybe a small single paragraph just with this mention.

**Comment by ericoporto** [comment]
Added an initial version here: https://github.com/adventuregamestudio/ags-manual/wiki/EditorLogPanel
