### ISSUE TITLE
Is SCR_NO_VALUE meant to be documented?

### ISSUE THREAD

**Issue by morganwillcock** [adventuregamestudio/ags-manual#222]
Is SCR_NO_VALUE meant to be documented?

It only appears in the manual in one place, but there is no explanation of what the value is or why this "None" value uses it while others do not:
```ags
enum CharacterDirection {
  eDirectionDown = 0,
  eDirectionLeft,
  eDirectionRight,
  eDirectionUp,
  eDirectionDownRight,
  eDirectionUpRight,
  eDirectionDownLeft,
  eDirectionUpLeft,
  eDirectionNone = SCR_NO_VALUE
};
```

**Comment by ivan-mogilko** [comment]
This constant is also usable in number of functions in order to define an argument of "no value".

For example:
```
cEgo.ChangeRoom(5, SCR_NO_VALUE, 100);
```

**Comment by ivan-mogilko** [comment]
`SCR_NO_VALUE` constant may be used in a number of functions when you want to skip certain optional arguments.

But it's not consistent for some reasons. For example:
```
clip.Play(SCR_NO_VALUE /*priority*/, eRepeat);
```
In this case priority will be assigned a clip's default, and eRepeat value used.

But in another case:
```
player.ChangeRoom(SCR_NO_VALUE, 100);
```
the engine only applies new position if all optional arguments have defined value.

---

On a side note, I question whether that is necessary to mention constant values in the manual, because that's of little use to users (and I don't think such things are usually documented?).

**Comment by morganwillcock** [comment]
Since it is potentially still used and is present in example code posted on the forum, I've added it to the constants page in the manual and to the syntax highlighters.
