### ISSUE TITLE
Figure it out why installation from free pascal is failing on Windows in GitHub Actions

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#247]
To be able to create a new release, the chmcmd build in the Windows CI was temporarily disabled here https://github.com/adventuregamestudio/ags-manual/commit/8b9292c372c4947b6b0fbf3df80fa7dbf459fa0a

Need to figure it out why it was failing - and only the windows one. Apparently nothing has changed on the downloads from Sourceforge. Maybe considering rehost them somewhere in GitHub ? I can't tell if it's a problem in the download or something that changed on the Windows itself on CI.

**Comment by ivan-mogilko** [comment]
Is the disabled task related to online manual pages not available?

**Comment by ericoporto** [comment]
I don't have a real device besides a phone now o
AND my internet connection is the worst possible at the moment .... But yes, because why I can't tell, I made it upload from the Linux build instead as I don't understand why the website is not building in the Windows build.

**Comment by ivan-mogilko** [comment]
Both chm and online version are built now.
It's best to not recreate manual tags anymore at the moment, I'm currently publishing 3.6.0 and 3.6.1 releases and I fear they may glitch building if manual tag gets deleted etc.

**Comment by ericoporto** [comment]
Sure, won't touch it more today :) will only have time to look into more detail in another day.

**Comment by morganwillcock** [comment]
It looks like a change in behaviour for the version of Curl that MSYS2 is using, where the downloaded file is actually being named "download" (i.e. the  `O` and `J` arguments do not seem to be working correctly).  It might be a bug in a very new version of Curl rather than something that was done on purpose, so it is probably best to wait a while and then test again.

**Comment by morganwillcock** [comment]
I think it will have built it, but it would not have been uploaded as an artifact because that step is filtered with `if: ${{ matrix.with-feature != null }}`. It does that to avoid uploading a duplicate for the second Windows build. The matrix sets a value for `with-feature`, but only one of the (included) Windows builds sets it.

Using a separate variable to control which builds will do an upload would make it easier to read. Or the Windows build could be changed to run both CHM compilers in the same environment (in separate build directories), although maybe that would make the error reporting harder to interpret.

**Comment by morganwillcock** [comment]
Fixed in df5ea0258bef6db4c8bf7b32c4a7bda41d562c82.
