### ISSUE TITLE
Guidelines for making screenshots

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags-manual#29]
I believe there should be a guideline for making screenshots for the manual.
IMHO usually the screenshot should be only large enough to display material that you are discussing.

For example, in this topic: https://github.com/adventuregamestudio/ags-manual/wiki/EditorInventoryItems
there is a large screenshot and like 2/3 of that screenshot is just a blank space.
I believe such thing should be avoided.

If you like to display multiple parts of the editor at the same time which are separated by empty space or unrelated controls, imho it's better to cut the larger screenshot into 2-3 smaller ones.
Since Editor supports moving/redocking panels, you may also rearrange controls to fit in a smaller area for some particular shot.
There's also a visual technique which proper name I do not know, it looks like making a "tearing" which cuts out either horizontal or vertical gap between two parts of the window on one screenshot. This may also be used.

Regarding the shown material, maybe we should find some open source game or an artist to make few demo assets? Because for example the key on the above screenshot looks a bit of lame in my opinion. (Mostly because of its size compared to the rest of window components)

**Comment by ericoporto** [comment]
Showing something from Dungeon Hands below

![image](https://user-images.githubusercontent.com/2244442/51570509-501c6580-1e86-11e9-8c4f-ad349a4a6d36.png)

Curious on your opinion of what's good and what's bad on this image - to provide replacement for the indicated image.

Now, about guidelines, I looked around and couldn't find much on this matter on github, but found some:
https://github.com/camunda/camunda-docs-manual#how-do-i-make-screenshots-for-documentation
https://github.com/keycloak/keycloak-documentation/blob/master/internal_resources/screenshots.adoc
https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/screenshots.md#screenshots

From erh... Research of those guides, I like the following lines:

Screenshots should be saved as PNG or JPG, with a width of at least 500 px. 
Try to keep file size less than 250KB.
Do not overuse screenshots. 
Do not rely on images to provide information or context.
Do not include any personally identifying information.
Capture just the part of the screen or window that users must focus on; do not include window headers in the final screenshots unless completely necessary.
Manipulate your screenshots to condense important information in them and limit empty GUI space and other inconsequential parts.
Do not include any watermark or any reference to other tool other than AGS in a screenshot.

Now just need to figure out a way to make the above lines a little shorter and figure where to add that - maybe an own manual section about contributing to the manual?

**Comment by selmiak** [comment]
I'm mostly with you there, I was wondering about that huge empty space too.
I'm against undocking and moving around the different window parts as the manual is for new users that will be totally confused when the screenshot looks totally different from what they have. 
It could help them realign their windows and get a better workflow, but when you start out you first want to get used to the basics before developing some kind of workflow.

What also sucks with the current invitem screenshot is that it is partially in german, I only noticed this way too late. But then I'd add this to then screenshot guidelines too.

ericos new screenshot is better but it goes against the rule of cutting the header etc, but that can easily be done afterwards. you could cut the header, the menu, and the icons, and the bottom grabber part, maybe even the in-engine explanation under the properties. 
The huge images in the 2 settings windows are good, this makes good use of the space, but what I'd like to see is a version with only 2 inventory items in the node tree and the project tree window pulled smaller to save space but still showing 1-3 of the _other_ options within the project tree window just so that a new user will find his way around this easier by seeing what is above and below that part of the editor. The order is always the same and only the icon might be hard to notice.
AND I'd also like to see an active rightclick context menu on the Inventory Item node to show everything possible.
This would also fit well in the screenshot guidelines: Show as much as possible
show rightclick context menus without overlapping other important aspects of the screenshot.

**Comment by ericoporto** [comment]
I like your comment @selmiak, looks like the proposed rules may be fitting! The need for guidelines @ivan-mogilko appointed is real, and it appears to be an useful simple tool to evaluate screenshot quality. I have to reflect on where to place it this rules text now!

**Comment by ericoporto** [comment]
I started to write a [CONTRIBUTING.md](https://github.com/ericoporto/ags-manual/blob/master/CONTRIBUTING.md) to include this requirement. Once I have this better figured out I will submit a PR.

**Comment by Scummbuddy** [comment]
I tried to clone the wiki so that I could create new screenshots (specifically the "images" folder) and push them back to master, but I couldn't find a proper way to do so. What I did instead was following this tutorial (https://ardalis.com/add-images-easily-to-github): 

- Open a New GitHub issue related to the project.
- Drag-and-drop my new image into the text field.
- GitHub will update image with a localized repository image URL.
- Copy that URL over into the Wiki page where I want it.

**Comment by morganwillcock** [comment]
I imagine this would break the builds for the CHM file and website, because the image files would need to be actually in the wiki repository to be cloned by the build processes.

What does git say when you try to push images back? You might be the first person to try who didn't already have some sort of repository access, so it would be good to work out a solution or find a better way to update the pages.

**Comment by ericoporto** [comment]
Done in https://github.com/adventuregamestudio/ags-manual/blob/master/CONTRIBUTING.md#how-to-add-screenshots-to-the-documentation
