### ISSUE TITLE
Move manual web building to a docker based building

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags-manual#48]
Building the web version hasn't been as repeatable as expected, even though things are very easy. We should have a docker environment with all dependencies, or a docker + script to get dependencies, to guarantee things reproduce. This will make eventually moving to a different ci system easier - be to appveyor itself, circle-ci, to azure, or to make travis itself more repeatable.

[Here is an example of a possible docker image](https://hub.docker.com/r/ericoporto/ags-manual)

**Comment by ericoporto** [comment]
This can make things even harder than they should and build is working fine now, so I am closing this.

**Comment by morganwillcock** [comment]
Just to note, I'm pretty sure that right now (after fixing more of my own self inflicted parallel sorting issues) if you override the timestamp for the build you should be able to checksum the build folders and the checksums should match between multiple runs. So in theory, we can now test builds on multiple operating systems and pandoc versions and see if any produce a different result (likely a CI task needs to pickup all checksums and compare them as a test job).

**Comment by ericoporto** [comment]
@morganwillcock thanks, this may be a new verify task, but this means building twice, once with a time stamp and once with a fixed one, and using only the fixed one for comparison, right?

**Comment by ericoporto** [comment]
Also, if you think this is important you can open a new issue for this test job.

**Comment by morganwillcock** [comment]
> but this means building twice, once with a time stamp and once with a fixed one, and using only the fixed one for comparison, right?

Yes, unless you can somehow pass the same datetime value to all jobs to ensure they use the same timestamp on the pages (on Windows I think the format is already slightly different, so even builds starting on the same second wouldn't work) or switch from using a timestamp to last commit ID.

But given that the build matrix to check all OS versions with all Pandoc versions would be quite large, just one more job for the actual deployment is probably not such a big deal in comparison.

> Also, if you think this is important you can open a new issue for this test job.

Possibly I will try to move everything to the single CI system first, so that the checksums are available on the same system.
