### ISSUE TITLE
Tips on resource management

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#72]
Add general explanation of how ags games handle resources
* which types of gfx, audio etc assets does ags project accept;
* how (what format) sprites are stored in compiled game;
* how assets affect perfomance (sprite cache, loading times etc)
* ways to reduce the size of game (compressing sprites, recoding audio to optimal quality and so on).

Original issue: https://github.com/adventuregamestudio/ags/issues/877

**Comment by ericoporto** [comment]
Wrote a sketch on the topic.

# Resource Management

The assets that gives your game graphics, music, voices and sound can impact your game footprint. Here are some general ideas around it.

## Graphics

Your game sprites are stored as bitmap files, and it's size will be proportional to the number of pixels stored, it will be normally packed along with your game executable. They are globbed sequentially, so for distribution systems that supports binary patching, like Steam, when you add a new sprite and update your game, only that single sprite will be delivered through it - Steam also applies a compression when sending these patches. If your game is distributed as a single binary file, ziping will reduce it's download size, but you can also turn on RLE compression on your game settings, which can reduce their size on disk.

You can generate some graphics programatically in your game using Dynamic Sprites, just remember if you don't unload and reload them between save and load, if you are using the savestate feature from AGS, this sprites will be serialized to the game savefiles, potentially making them of a significant size.

## Audio

AGS stores audio files directly from their imported files, and can be globed as an external audio.vox file or be part of the main game executable. Speech is always packed as an external speech.vox file. The file doesn't compress the audio, but instead relies on the original compression from each individually imported audio file. Some distribution platforms don't provide binary patching, since audio files tend to be less volatile at middle to late parts of game development, it may be wise to have them as external files so that they are not downloaded again by your player.

### Speech

Usually the ogg format can achieve good compression with voice files. If you use Audacity, a compression of 3 (of 10) provides good quality while providing very small files.

### Sound Effects

For sound effect files, usually ogg provides a good compression, you may need to test individual compression levels.

### Music

Music files are usually long files where audio does different patterns with a rithm. This type of audio tend to compress better with the mp3 format, but long ambient sounds may compress better with ogg. It's a good idea to experiment. Don't use wav files for music or it will make your game size too big without perceptual quality gains.

**Comment by rofl0r** [comment]
the part about Music->mp3 isn't correct. ogg has better quality/compression for any given input. also usage of mp3 is problematical because it is patented and license fees have to be paid. i'm pretty sure the artists aren't aware of that.

the key thing needed to be stated here is what bitrates and format settings should be chosen. for example, 8 bit mono at 22.05 Khz is perfectly fine for speech.

**Comment by fernewelten** [comment]
Also, .mp3 audio files don't loop well. As far as I understand, the compression algorithm brings them to quantized size, and the exact loop size is nearly always a bit different from that quantized size. Thus, looped .mp3 files are prone to clicks and tiny pauses at the repeat point. .ogg files don't have this problem.

**Comment by ericoporto** [comment]
MP3 patents have dropped, so no, you can use freely. About looping and clicking, audio format doesn't matter, see here -> https://github.com/adventuregamestudio/ags/issues/501 . I listen music on Totem Movie Player and mp3 doesn't have a gap there, or ogg, or Wav. I can record output with audacity and show the wave sound. I can change the text to rely that there's no significant difference between ogg and mp3 for music.

**Comment by sonneveld** [comment]
> also usage of mp3 is problematic because it is patented and license fees have to be paid.

The patent issue hasn't been true for a few years now. The advantage of ogg is that it supports gapless playback, which is useful for looping audio.

> the key thing needed to be stated here is what bitrates and format settings should be chosen. for example, 8 bit mono at 22.05 Khz is perfectly fine for speech.

er is it? I realise we're discussing subjective audio quality, but I would argue 16bit mono is probably fine. I recommend being conservative what we're suggesting here unless we want to end up with a bunch of new AGS games that sound bad when wearing headphones.

**Comment by rofl0r** [comment]
> unless we want to end up with a bunch of new AGS games that sound bad when wearing headphones

you can test my recommended ffmpeg settings with my [repack of metaphobia](http://ftp.barfooze.de/pub/sabotage/tmp/Metaphobia_repack.7z)

**Comment by rofl0r** [comment]
> MP3 patents have dropped, so no, you can use freely. 

according to this article: https://www.theregister.co.uk/2017/05/16/mp3_dies_nobody_noticed/

"So yup, now you can use MP3 encoding in your products almost patent free"

"almost" isn't "entirely"

**Comment by fernewelten** [comment]
Concerning the quantizing: I've looked it up. .mp3 files can only have an integer number of MPEG 1 layer 3 frrames, where a frame contains exactly 1152 samples. If you compress a file that is shorter than that, then the last frame will be filled up.

So if you want to loop an .mp3 file, you're in for some hassle: You need to stretch the source material, recoding it, to bring it up to an integer number of frames, or you'll get a gap when looping.

This is entirely different from the question of whether the _player_ is up to the task of looping.

**Comment by sonneveld** [comment]
> according to this article: https://www.theregister.co.uk/2017/05/16/mp3_dies_nobody_noticed/
> "So yup, now you can use MP3 encoding in your products almost patent free"
> "almost" isn't "entirely"

Fedora is quite happy to include MP3 support now https://fedoramagazine.org/full-mp3-support-coming-soon-to-fedora/ so I'm happy to lean on their legal team for this.

**Comment by sonneveld** [comment]
> you can test my recommended ffmpeg settings with my [repack of metaphobia](http://ftp.barfooze.de/pub/sabotage/tmp/Metaphobia_repack.7z)

I don't have golden ears but I can definitely hear a difference when you down convert to 8bit before encoding to ogg. Saying that, the original audio probably doesn't need to be stereo 320kbps either.

[You794-compare.zip](https://github.com/adventuregamestudio/ags-manual/files/3425073/You794-compare.zip)

Also, I noticed agspack seems to stomp over the libname, replacing it with "AGSPACK3...". That field should usually have the original library filename. That way you can still figure out what it used to be even if part of an exe.

**Comment by rofl0r** [comment]
> I don't have golden ears but I can definitely hear a difference when you down convert to 8bit before encoding to ogg.

right, there's indeed a noticable difference if you compare one speech sample with the other. but if you just play the game with the downsampled speech, you won't notice anything odd, and the speech will sound just fine.

**Comment by sonneveld** [comment]
> but if you just play the game with the downsampled speech, you won't notice anything odd, and the speech will sound just fine.

This is getting to be too subjective for me. I'm just going to agree to disagree.

**Comment by ivan-mogilko** [comment]
A note regarding MP3 licensing, for many years AGS was distributed with 2 engines: one with mp3 and one without mp3 support. I stopped doing this since 3.4.3, but in case this issue resurfaces we may again provide no-mp3 engine.

**Comment by ericoporto** [comment]
About looping, if the player (AGS) ldoesn't support gapless loop, this point doesn't matter. Right now I think gapless playback is only possible using agswaves plug-in.

About compression in general, there's no magic formula, better to test. One thing that I want to strees somewhere is that's a good idea to keep your original files in wav or aiff format and try different compressions, which can usually be batched in the audio software.

One thing to keep in mind is that people just starting with AGS are probably the first readers this page should appeal. I would imagine many will look for online resources, so I wouldn't want the person to read this as mandatory for distributing their game but more on recommend things to keep in mind as good practices.

Overall I find I don't mind the download size on PC, since AGS games are generally pretty small. I rapidly mentioned patching because global compressions are usually bad for distribution systems that offer patching, since they usually provide per patch compression and need uncompressed files to calculate patches.

About graphics, my understanding is that there's nothing to be done unless the sprite blob is stored in png instead of bmp and the engine is modified to read it.

**Comment by rofl0r** [comment]
> we may again provide no-mp3 engine

i don't think that's necessary, it should be sufficient to advise game creators to use .ogg instead.

**Comment by ericoporto** [comment]
@rofl0r you had a detailed explanation of the Metaphobia repack somewhere or I am dreaming? I looked in the forums and here and couldn't findout. Can you detail the process please?

**Comment by ivan-mogilko** [comment]
@ericoporto there are links are in the first comment in the linked ticket: <https://github.com/adventuregamestudio/ags/issues/877>

**Comment by ericoporto** [comment]
Added a note on commit [`6b53e4d`](https://github.com/adventuregamestudio/ags-manual/wiki/_compare/d1e81cf045eb8582640222a9db133166ed12db00...6b53e4d76a6bf8ac29ce2a0b4bd852286bed94fa) of the manual.
