### ISSUE TITLE
Index shortcuts missing

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#86]
I was comparing old and new CHM and noticed that in new CHM there are no short index entries for functions. In old one you could e.g. type `Walk` and it would link to `Character.Walk`, in the new one you must type full `Character.Walk` name.

It could be that old system was also adding `\subsection` names from TEX into index. For instance, original header for "Walk" was:
<pre>
\subsection{Walk}\label{Character.Walk}\index{Character.Walk}\index{MoveCharacter}\index{MoveCharacterBlocking}\index{MoveCharacterDirect}</pre>

One issue though, those functions that were present in multiple classes had name of type manually added in subsection name, for example:
<pre>\subsection{Move (character)}\label{Character.Move}\index{Character.Move}`
\subsection{Move (object)}\label{Object.Move}\index{Object.Move}\index{MoveObject}\index{MoveObjectDirect}</pre>

So I guess that doing this manually all time could become tiresome and error prone.
I wonder, if there could be way for a script to take out class member function and add an index entry which is either "FuncName" or "FuncName (typename)" depending on whether there are functions of same name in other classes? Is it too complicated to do so?

**Comment by morganwillcock** [comment]
This is possible to do, but it will extend the index by 406 entries (plus one entry for every object member that exists with the same name somewhere else). I see your point, that it doesn't do the same thing as it did before, but I'd suggest that the index is now actually readable because it is much shorter.

<pre>
ActiveInventory
ActiveOptionID
Add
AddInventory
AddItem
AddWaypoint
Animate
Animating
AnimationSpeed
AnimationStopTimeMargin
Append
AppendChar
ArcCos
ArcSin
ArcTan
ArcTan2
AsFloat
AsInt
AsType
AudioChannelCount
AudioChannels
AudioClipCount
AudioClips
AutoTracking
BackgroundGraphic
Baseline
BlinkInterval
BlinkView
BlinkWhileThinking
BlockingHeight
BlockingWidth
BottomEdge
BringToFront
Camera
CapsLock
Centre
ChangeCanvasSize
ChangeModeGraphic
ChangeModeHotspot
ChangeModeView
ChangeRoom
ChangeRoomAutoPosition
ChangeTranslation
ChangeView
CharacterCount
CharacterToUse
Chars
Clear
Click
Clickable
ClipImage
Close
ColorDepth
CompareStyle
CompareTo
Contains
ControlCount
ControlEnabled
Controls
Copy
CopyTransparencyMask
Cos
Cosh
Create
CreateCopy
CreateFromBackground
CreateFromDrawingSurface
CreateFromExistingSprite
CreateFromFile
CreateFromSaveGame
CreateFromScreenShot
CreateGraphical
CreateTextual
Crop
CursorGraphic
CustomPortraitPlacement
DayOfMonth
DegreesToRadians
Delete
DestinationX
DestinationY
DiagonalLoops
DialogCount
DialogToRender
DisableMode
DisplayOptions
DisplayPostTimeMs
DoOnceOnly
DrawCircle
DrawImage
DrawingColor
DrawLine
DrawMessageWrapped
DrawPixel
DrawRectangle
DrawString
DrawStringWrapped
DrawSurface
DrawTriangle
Enabled
EnableMode
EndsWith
EOF
Error
Exists
Exp
FaceCharacter
FaceDirection
FaceLocation
FaceObject
FileName
FileType
FillDirList
FillSaveGameList
FindWordID
Flip
Flipped
FollowCharacter
Font
FontCount
Format
Frame
Gamma
Get
GetAtRoomXY
GetAtScreenXY
GetColorFromRGB
GetDrawingSurface
GetDrawingSurfaceForBackground
GetFrameCountForLoop
GetItemAtLocation
GetItemsAsArray
GetKeysAsArray
GetLocationName
GetLoopCountForView
GetModeGraphic
GetOptionState
GetOptionText
GetPixel
GetProperty
GetRunNextSettingForLoop
GetSaveSlotDescription
GetTextProperty
GetValuesAsArray
GetViewFrame
GlobalMessages
GlobalSpeechAnimationDelay
GlobalStrings
Graphic
GUICount
HandleGraphic
HandleOffset
HardwareAcceleration
HasAlphaChannel
HasExplicitLight
HasExplicitTint
HasInputFocus
HasInventory
HasOptionBeenChosen
Height
HideBorder
HideScrollArrows
Hour
ID
IdleView
IgnoreLighting
IgnoreScaling
IgnoreUserInputAfterTextTimeoutMs
IgnoreWalkbehinds
IndexOf
InputBox
InsertItemAt
InSkippableCutscene
InventoryItemCount
InventoryQuantity
IsAudioPlaying
IsAvailable
IsButtonDown
IsCollidingWithChar
IsCollidingWithObject
IsInteractionAvailable
IsModeEnabled
IsNullOrEmpty
IsPlaying
IsPluginLoaded
ItemAtIndex
ItemCount
ItemHeight
Items
ItemsPerRow
ItemWidth
LeftEdge
Length
LengthMs
LightLevel
LinkedAudio
LockView
LockViewAligned
LockViewFrame
LockViewOffset
Log
Log10
Loop
LoseInventory
LowerCase
ManualScaling
Max
MergeIntoBackground
Messages
Min
MinimumTextDisplayTimeMs
Minute
Mode
Month
MouseCursorCount
MouseOverGraphic
Move
MovementLinkedToAnimation
Moving
MusicOnLoad
Name
NormalFont
NormalGraphic
NormalView
Now
NumLock
ObjectCount
Open
OperatingSystem
OptionCount
OwningGUI
Panning
ParserTextBoxWidth
ParserTextBoxX
ParserTextBoxY
ParseText
Pi
PlaceOnWalkableArea
Play
PlayFrom
PlayingClip
PlayQueued
PortraitXOffset
PortraitY
Position
PositionMs
PreviousRoom
ProcessClick
PushedGraphic
RadiansToDegrees
RaiseToPower
RawTime
ReadInt
ReadRawChar
ReadRawInt
ReadRawLineBack
ReadStringBack
Release
Remove
RemoveItem
RemoveTint
RenderAtScreenResolution
Replace
ReplaceCharAt
Resize
RightEdge
Room
RoomToScreenPoint
Rotate
RowCount
RunActiveOption
RunInteraction
RuntimeInfo
Said
SaidUnknownWord
SaveCursorUntilItLeaves
SaveGameSlots
SaveToFile
Say
SayAt
SayBackground
ScaleMoveSpeed
ScaleVolume
Scaling
ScreenHeight
ScreenToRoomPoint
ScreenWidth
ScrollDown
ScrollLock
ScrollUp
Second
Seek
SelectedIndex
SelectNextMode
SelectPreviousMode
SendToBack
Set
SetAsPlayer
SetAt
SetAudioTypeSpeechVolumeDrop
SetAudioTypeVolume
SetBounds
SetHasOptionBeenChosen
SetIdleView
SetLightLevel
SetOptionState
SetPosition
SetProperty
SetRoomLocation
SetSaveGameDirectory
SetSize
SetText
SetTextProperty
SetView
SetWalkSpeed
ShowTextParser
Sin
Sinh
SkipKey
SkippingCutscene
SkipStyle
Solid
SortStyle
Speaking
SpeakingFrame
SpeechAnimationDelay
SpeechColor
SpeechFont
SpeechView
Speed
SpriteHeight
SpriteWidth
Sqrt
Start
StartsWith
Stop
StopAnimating
StopAudio
StopMoving
Style
Substring
SupportsGammaControl
Surface
Tan
Tanh
Text
TextAlignment
TextColor
TextReadingSpeed
Think
Thinking
ThinkingFrame
ThinkView
Tint
TintBlue
TintEnabled
TintGreen
TintLuminance
TintRed
TintSaturation
TopEdge
TopItem
Translated
TranslationFilename
Transparency
Truncate
TurnBeforeWalking
Type
UnlockView
Update
UpperCase
UseDefaultGraphic
UseGlobalSpeechAnimationDelay
UseHighResCoordinates
UseModeGraphic
UseNativeCoordinates
Valid
Value
Version
View
ViewCount
ViewportHeight
ViewportWidth
Visible
VoiceMode
Volume
VSync
Walk
WalkSpeedX
WalkSpeedY
WalkStraight
WalkToX
WalkToY
Width
Windowed
WriteInt
WriteRawChar
WriteRawLine
WriteString
X
x
X
Y
y
Year
z
ZOrder
</pre>

**Comment by ivan-mogilko** [comment]
This was the way I was quickly searching for functions all those years. What about others, do you always type full type name with a dot?

**Comment by morganwillcock** [comment]
As an example of what it is currently in the index:

- "Upgrading from a previous version" (anything that is classed as just a help topic)
- Dictionary
- Dictionary.Clear
